---
title: "12 Other Data Visualization Options"
author: "Gustavo R. Santos (original) | Antti Rask (modifications)"
date: "2022-08-29"
output: html_document
---

# Other Data Visualization Options
 
## Load Libraries

```{r, message=FALSE, warning=FALSE}
library(conflicted) # An Alternative Conflict Resolution Strategy
library(officer)    # Manipulation of Microsoft Word and PowerPoint Documents
library(tidytext)   # Text Mining using 'dplyr', 'ggplot2', and Other Tidy Tools
library(tidyverse)  # Easily Install and Load the 'Tidyverse'
library(wordcloud2) # Create Word Cloud by 'htmlwidget' 
```

## Plotting Graphic in Microsoft Power BI

```{r}
# Data frame created
dataset <- tibble(
  dist1 = rnorm(100),
  dist2 = runif(100)
)

# Save to disk
write_csv(data, "data/example_data.csv")
```

```{r}
# To plot this graphic in Power BI, copy and paste this code in the tool
ggplot(dataset) %>%
  geom_histogram(
    aes(dist1),
    bins  = 10,
    color = "white",
    fill  = "royalblue"
  ) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_classic()
```
```{r}
dataset <- tibble(dist1 = data %>% pull(dist1))

head(dataset)
```

Antti: At the time of writing, the word document (of Chapter 10 of the book) is missing from the original repo. I will include the original code as a placeholder, but will update it as soon as the word document is available.

## Word cloud

```{r}
# Read word document
chapter10 <- read_docx("data/Data_Wrangling_With_R_Chapter10.docx")
content   <- docx_summary(chapter10)

# Extract only textual information and drop Blank cells and NAs
text <- content %>% 
  select(text) %>% 
  na_if("") %>% 
  drop_na()

# Transform to tibble object
text <- tibble(text)
```

```{r}
# Tokenize - one word is one token
text_tokens <- text %>%
  unnest_tokens(output = word, input = text)
```

```{r}
# Remove numbers and punctuation
clean_tokens <- text_tokens %>%
 filter(str_detect(word, "\\D")) %>%
 filter(!str_detect(word, "[:punct:]"))
```

```{r}
# load stopwords
data(stop_words)

# Anti-join: keep only what is not in stop words
clean_tokens <- clean_tokens %>%
  anti_join(stop_words)
```

```{r}
# Count word frequency.
word_freq <- clean_tokens %>%
  count(word, sort = TRUE)
```

```{r}
# Generating WordCloud
wordcloud2(data = word_freq, color = "random-dark", size = 1)
```
